substitutions:
  btn_gpio:  GPIO8
  light_gpio: GPIO19
  pa_pin: GPIO38

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    advanced:
      minimum_chip_revision: "3.0"
    type: esp-idf
    sdkconfig_options:
        CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP_TLS_INSECURE: "y"
        CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY: "y"
        CONFIG_MBEDTLS_CERTIFICATE_BUNDLE: "y"


psram:
  mode: octal
  speed: 80MHz


external_components:
  - source:
      type: git
      url: https://github.com/dwitgen/esphome-es8311
      ref: main
      path: .
    components: [es8311]

# ---------------------------------------------------------
# Hardware & Audio Configuration
# ---------------------------------------------------------

i2c:
  sda: GPIO1
  scl: GPIO2
  id: i2c_bus
  frequency: 600kHz
  scan: True


# ---------------------------------------------------------
# Native Audio Components
# ---------------------------------------------------------

i2s_audio:
  # BUS A: For the Speaker (ES8311 Codec)
  - id: i2s_speaker_bus
    i2s_mclk_pin: GPIO42
    i2s_lrclk_pin: GPIO41
    i2s_bclk_pin: GPIO40
    #use_legacy: true

  # BUS B: For the Microphone (ES7210 ADC)
  - id: i2s_mic_bus
    i2s_mclk_pin: GPIO20
    i2s_lrclk_pin: GPIO9
    i2s_bclk_pin: GPIO10

# Driver for the ES8311 DAC (Speaker Chip)
audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: i2c_bus
    sample_rate: 16000
    bits_per_sample: 16bit

# Driver for the ES7210 ADC (Microphone Chip)
audio_adc:
  - platform: es7210
    id: es7210_adc
    i2c_id: i2c_bus
    mic_gain: 21 # Adjustable gain (0dB to 45dB)


# Microphone Entity
microphone:
  - platform: i2s_audio
    id: korvo_mic
    i2s_audio_id: i2s_mic_bus
    sample_rate: 16000
    i2s_din_pin: GPIO11
    bits_per_sample: 16bit
    adc_type: external

# Speaker Entity with mixer and resamplers to keep sample rate from changing during transition from tts to media
speaker:
  - platform: i2s_audio
    id: korvo_speaker
    i2s_audio_id: i2s_speaker_bus
    i2s_dout_pin: GPIO39
    dac_type: external
    sample_rate: 16000
    bits_per_sample: 16bit
    channel: left
    audio_dac: es8311_dac
    buffer_duration: 500ms
    i2s_mode: primary

  - platform: mixer
    id: main_speaker
    output_speaker: korvo_speaker
    source_speakers:
      - id: tts_mixer_input
      - id: media_mixer_input

  - platform: resampler
    id: tts_input
    output_speaker: tts_mixer_input
    sample_rate: 48000

  - platform: resampler
    id: media_input
    output_speaker: media_mixer_input
    sample_rate: 48000

# Light Entity
light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "${friendly_name} Light"
    pin: ${light_gpio}
    num_leds: 12
    rgb_order: GRB
    chipset: ws2812
    default_transition_length: 0s
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - addressable_twinkle:
          name: "Working"
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_color_wipe:
          name: "Wakeword"
          colors:
            - red: 28%
              green: 100%
              blue: 90%
              num_leds: 12
          add_led_interval: 40ms
          reverse: false
      - addressable_color_wipe:
          name: "Connecting"
          colors:
            - red: 60%
              green: 60%
              blue: 60%
              num_leds: 12
            - red: 60%
              green: 60%
              blue: 0%
              num_leds: 12
          add_led_interval: 100ms
          reverse: true
      - addressable_color_wipe:
          name: "Thinking"
          colors:
            - red: 1%
              green: 90%
              blue: 99%
              num_leds: 2
            - red: 13%
              green: 17%
              blue: 87%
              num_leds: 6
          add_led_interval: 75ms
          reverse: true
      - pulse:
          name: "Slow Pulse"
          transition_length: 0.5s
          update_interval: 1s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 50ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

# Button Entity
binary_sensor:
  - platform: template
    id: btn_vol_up
    internal: true

  - platform: template
    id: btn_vol_down
    internal: true

  - platform: template
    id: btn_set
    internal: true

  - platform: template
    id: btn_play
    internal: true

  - platform: template
    id: btn_mode
    internal: true

  - platform: template
    id: btn_record
    internal: true


sensor:
  - id: button_adc
    name: "${friendly_name} Button ADC"
    platform: adc
    internal: true
    pin: ${btn_gpio}
    attenuation: auto
    update_interval: 50ms
    filters:
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1
      - delta: 0.1

    on_value_range:
      - below: 0.55
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons
                - lambda: id(btn_vol_up).publish_state(true);

      - above: 0.65
        below: 0.92
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons
                - lambda: id(btn_vol_down).publish_state(true);

      - above: 1.02
        below: 1.33
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons
                - lambda: id(btn_set).publish_state(true);

      - above: 1.43
        below: 1.77
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons
                - lambda: id(btn_play).publish_state(true);

      - above: 1.87
        below: 2.15
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons
                - lambda: id(btn_mode).publish_state(true);

      - above: 2.25
        below: 2.56
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons
                - lambda: id(btn_record).publish_state(true);

      - above: 2.8
        then:
          - if:
              condition:
                lambda: return !id(init_in_progress);
              then:
                - script.execute: clear_buttons

# PA control
output:
  - platform: gpio
    pin: ${pa_pin}
    id: amp_pin

# Board scripts
script:
  - id: clear_buttons
    then:
      - lambda: |-
          id(btn_vol_up).publish_state(false);
          id(btn_vol_down).publish_state(false);
          id(btn_set).publish_state(false);
          id(btn_play).publish_state(false);
          id(btn_mode).publish_state(false);
          id(btn_record).publish_state(false);




